/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;

/**
 *
 * @author joelpinheiro
 */
public class SimulatorUI extends javax.swing.JFrame {

    public void BPM() {
        dstorage.setVisible(true);
        dworkshop.setVisible(false);
        dstore.setVisible(false);
    }
    
    /**
     * Creates new form NewJFrame1
     */
    public SimulatorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel1 = new graphics.ImagePanel();
        a1working = new javax.swing.JLabel();
        a2working = new javax.swing.JLabel();
        a3working = new javax.swing.JLabel();
        c1outside = new javax.swing.JLabel();
        c2outside = new javax.swing.JLabel();
        c3outside = new javax.swing.JLabel();
        dstore = new javax.swing.JLabel();
        a1waiting = new javax.swing.JLabel();
        a2waiting = new javax.swing.JLabel();
        a3waiting = new javax.swing.JLabel();
        c1buying = new javax.swing.JLabel();
        c2buying = new javax.swing.JLabel();
        c3buying = new javax.swing.JLabel();
        c3appraising = new javax.swing.JLabel();
        c2appraising = new javax.swing.JLabel();
        c1appraising = new javax.swing.JLabel();
        dworkshop = new javax.swing.JLabel();
        dstorage = new javax.swing.JLabel();
        a1death = new javax.swing.JLabel();
        a2death = new javax.swing.JLabel();
        a3death = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        a1working.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/a1.png"))); // NOI18N

        a2working.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/a2.png"))); // NOI18N

        a3working.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/a3.png"))); // NOI18N

        c1outside.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/c1.png"))); // NOI18N

        c2outside.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/c2.png"))); // NOI18N

        c3outside.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/c3.png"))); // NOI18N

        dstore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/d.png"))); // NOI18N

        a1waiting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/a1.png"))); // NOI18N

        a2waiting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/a2.png"))); // NOI18N

        a3waiting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/a3.png"))); // NOI18N

        c1buying.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/c1.png"))); // NOI18N

        c2buying.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/c2.png"))); // NOI18N

        c3buying.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/c3.png"))); // NOI18N

        c3appraising.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/c3.png"))); // NOI18N

        c2appraising.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/c2.png"))); // NOI18N

        c1appraising.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/c1.png"))); // NOI18N

        dworkshop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/d.png"))); // NOI18N

        dstorage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/d.png"))); // NOI18N

        a1death.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/a1.png"))); // NOI18N

        a2death.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/a2.png"))); // NOI18N

        a3death.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images/a3.png"))); // NOI18N

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(imagePanel1Layout.createSequentialGroup()
                        .addComponent(c1appraising)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c2appraising)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c3appraising)
                        .addGap(105, 105, 105)
                        .addComponent(c1buying)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c2buying)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c3buying)
                        .addGap(84, 84, 84)
                        .addComponent(dstore)
                        .addGap(70, 70, 70)
                        .addComponent(c1outside)
                        .addGap(0, 0, 0)
                        .addComponent(c2outside)
                        .addGap(0, 0, 0)
                        .addComponent(c3outside))
                    .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createSequentialGroup()
                            .addGap(128, 128, 128)
                            .addComponent(a1working)
                            .addGap(81, 81, 81)
                            .addComponent(a2working)
                            .addGap(72, 72, 72)
                            .addComponent(a3working)
                            .addGap(68, 68, 68)
                            .addComponent(a1waiting)
                            .addGap(0, 0, 0)
                            .addComponent(a2waiting)
                            .addGap(0, 0, 0)
                            .addComponent(a3waiting)
                            .addGap(86, 86, 86)
                            .addComponent(a1death)
                            .addGap(0, 0, 0)
                            .addComponent(a2death)
                            .addGap(0, 0, 0)
                            .addComponent(a3death))
                        .addGroup(imagePanel1Layout.createSequentialGroup()
                            .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dworkshop)
                                .addComponent(dstorage))
                            .addGap(714, 714, 714))))
                .addGap(347, 347, 347))
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createSequentialGroup()
                .addContainerGap(331, Short.MAX_VALUE)
                .addComponent(dstorage)
                .addGap(92, 92, 92)
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(a1death)
                        .addComponent(a2death)
                        .addComponent(a3death))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(a1waiting)
                        .addComponent(a2waiting)
                        .addComponent(a3waiting)
                        .addComponent(a1working)
                        .addComponent(a2working)
                        .addComponent(a3working)))
                .addGap(10, 10, 10)
                .addComponent(dworkshop)
                .addGap(95, 95, 95)
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(c1outside)
                        .addComponent(c2outside)
                        .addComponent(c3outside)
                        .addComponent(dstore))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(c1buying)
                        .addComponent(c2buying)
                        .addComponent(c3buying)
                        .addComponent(c1appraising)
                        .addComponent(c2appraising)
                        .addComponent(c3appraising)))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulatorUI().setVisible(true);
            }
        });
    }
    
    public void showSimulatorUI() {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulatorUI().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1death;
    private javax.swing.JLabel a1waiting;
    private javax.swing.JLabel a1working;
    private javax.swing.JLabel a2death;
    private javax.swing.JLabel a2waiting;
    private javax.swing.JLabel a2working;
    private javax.swing.JLabel a3death;
    private javax.swing.JLabel a3waiting;
    private javax.swing.JLabel a3working;
    private javax.swing.JLabel c1appraising;
    private javax.swing.JLabel c1buying;
    private javax.swing.JLabel c1outside;
    private javax.swing.JLabel c2appraising;
    private javax.swing.JLabel c2buying;
    private javax.swing.JLabel c2outside;
    private javax.swing.JLabel c3appraising;
    private javax.swing.JLabel c3buying;
    private javax.swing.JLabel c3outside;
    private javax.swing.JLabel dstorage;
    private javax.swing.JLabel dstore;
    private javax.swing.JLabel dworkshop;
    private graphics.ImagePanel imagePanel1;
    // End of variables declaration//GEN-END:variables
}
